from dotenv import load_dotenv
import os

load_dotenv()

TELETHON_ACCESS_HASH = os.getenv("TELETHON_ACCESS_HASH")
TELETHON_API_ID = os.getenv("TELETHON_API_ID")
TELETHON_API_HASH = os.getenv("TELETHON_API_HASH")
TELETHON_SESSION_STRING = os.getenv("TELETHON_SESSION_STRING")

CLOUDFLARE_ACCOUNT_IDENTIFIER = os.getenv("CLOUDFLARE_ACCOUNT_IDENTIFIER")
CLOUDFLARE_DATABASE_IDENTIFIER = os.getenv("CLOUDFLARE_DATABASE_IDENTIFIER")
CLOUDFLARE_API_TOKEN = os.getenv("CLOUDFLARE_API_TOKEN")

PYTHON_ENVIRONMENT = os.getenv("PYTHON_ENVIRONMENT")

STICKER_PACK_IDS = os.getenv("STICKER_PACK_IDS").split(",")
